name: networks.perspective_net

perspective_decoder:
  name: decoders.perspective_decoder

  latitude_decoder:
    name: decoders.latitude_decoder
    use_tanh: false
    decoder:
      name: decoders.persformer_decoder
      predict_uncertainty: false
      use_original_architecture: true

  up_decoder:
    name: decoders.up_decoder
    decoder:
      name: decoders.persformer_decoder
      predict_uncertainty: false
      use_original_architecture: true

backbone:
  name: encoders.mix_vit

ll_enc:
  name: encoders.low_level_encoder
  keep_resolution: false

param_net:
  name: networks.param_net
  original_weights: true

  backbone:
    name: encoders.convnext
    num_classes: 5

param_opt: null
