seed: 0
num_steps: 45_000

writer: none
log_every_iter: 500
eval_every_iter: 1000

lr: 0.01
clip_grad: 1.0
optimizer: sgd
optimizer_options:
  weight_decay: 0.0001
  momentum: 0.9

lr_schedule:
  type: SequentialLR
  on_epoch: false
  options:
    milestones: [1_000]
    schedulers:
      - type: LinearLR
        options:
          start_factor: 1e-3
          total_iters: 1_000
      - type: MultiStepLR
        options:
          gamma: 0.1
          milestones: [30_000, 40_000]

submodules: []

median_metrics:
  - roll_opt_error
  - pitch_opt_error
  - gravity_opt_error
  - vfov_opt_error
  - up_angle_error
  - latitude_angle_error
  - up_angle_recall@1
  - up_angle_recall@5
  - up_angle_recall@10
  - latitude_angle_recall@1
  - latitude_angle_recall@5
  - latitude_angle_recall@10

recall_metrics:
  roll_opt_error: [1, 3, 5, 10]
  pitch_opt_error: [1, 3, 5, 10]
  gravity_opt_error: [1, 3, 5, 10]
  vfov_opt_error: [1, 3, 5, 10]

plot: [3, "siclib.visualization.visualize_batch.make_perspective_figures"]
