defaults:
  - train: perspective-fields
  - model: perspective-net-orig
  - data: openpano
  - _self_

data:
  train_batch_size: 64
  val_batch_size: 64
  test_batch_size: 64

model:
  backbone:
    weights: weights/ade_pretrained.pth # TODO: update this path
